### ISSUE TITLE
How to contact for dataset that use in the paper?

### ISSUE THREAD

**Issue by Paopasatiht** [yuhao-nie/Stanford-solar-forecasting-dataset#1]
[Dataset Paper](https://github.com/yuhao-nie/Stanford-solar-forecasting-dataset/blob/main) | [Benchmark Dataset Repository](https://github.com/yuhao-nie/Stanford-solar-forecasting-dataset/blob/main) | [Raw Dataset Repository](https://github.com/yuhao-nie/Stanford-solar-forecasting-dataset/blob/main)

this 3 doesn't work. 
Do I need to contact who to access ?
Do outsider have right to access or not?

Now I'm interest for using the cloud image to make a solar forecast project too. :)

 @yuhao-nie @5Summer

**Comment by yuhao-nie** [comment]
The links should work now
