### ISSUE TITLE
About Research Equipment.

### ISSUE THREAD

**Issue by kaizhai** [yuhao-nie/Stanford-solar-forecasting-dataset#6]
Hello, I would like to ask if you have used the Hikvision DS-2CD6362F-IV2, a 6-megapixel camera, in your paper. However, in my country, it seems that only 5-megapixel cameras are available,Hikvision DS-zXA3956F.Can I use the data captured by such a camera with your code?Can it withstand outdoor environments?

**Comment by yuhao-nie** [comment]
I think it should also work with the 5-megapixel camera. If you want it last longer, you need to do regular maintenance and install some water/dust-proof housing.
